name: Auto Update
on:
  schedule:
    - cron: '10 * * * *'
  workflow_dispatch:

jobs:
  auto-update:
    name: Auto Update
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          token: ${{ secrets.GH_TOKEN }}
      - uses: actions/setup-java@v4
        name: Setup Java
        with:
          distribution: 'temurin'
          java-version: 17
      - uses: gradle/wrapper-validation-action@v2
        name: Validate Gradle Wrapper
      - uses: gradle/actions/setup-gradle@v3
        name: Setup Gradle
      - name: Update Version
        run: ./gradlew update --ci --no-daemon
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
